name: "Deploy to GitHub "
on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore WoTModAssistantPlus/WoTModAssistantPlus.csproj

      - name: Build project
        run: dotnet build WoTModAssistantPlus/WoTModAssistantPlus.csproj -c Release --no-restore

      - run: dotnet publish WoTModAssistantPlus/WoTModAssistantPlus.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true 